initial_positions:
  ur_elbow_joint: 1.57
  ur_shoulder_lift_joint: -1.57
  ur_shoulder_pan_joint: 0.0
  ur_wrist_1_joint: 0.0
  ur_wrist_2_joint: 1.57
  ur_wrist_3_joint: 0.0
  gripper_soft_robotics_gripper_left_finger_joint1: 0.0
  gripper_soft_robotics_gripper_right_finger_joint1: 0.0
