# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - joint_trajectory_controller
    - gripper_controller

  joint_trajectory_controller:
    type: FollowJointTrajectory
    joints:
      - ur_shoulder_pan_joint
      - ur_shoulder_lift_joint
      - ur_elbow_joint
      - ur_wrist_1_joint
      - ur_wrist_2_joint
      - ur_wrist_3_joint
    action_ns: follow_joint_trajectory
    default: true

  gripper_controller:
      type: FollowJointTrajectory
      joints:
        - gripper_soft_robotics_gripper_left_finger_joint1
        - gripper_soft_robotics_gripper_right_finger_joint1
      action_ns: follow_joint_trajectory
      default: true
